version: "3.9"

services:
  postgres:
    image: "postgres:16.1-alpine"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_NAME}
  app:
    build: .
    restart: unless-stopped
    command: uvicorn --host 0.0.0.0 --port 8080 --workers 4 --log-level trace asgi:application
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    expose:
      - "8080"
    env_file:
      - .env
    depends_on:
      - postgres
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "${VIRTUAL_PORT}"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/media
    depends_on:
      - app
    networks:
      - nginx-proxy
      - default

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
    nginx-proxy:
        external:
            name: net-nginx-proxy
